const errMsg = {
    "AUD": {Value: "Отсутствует"},
    "AZN": {Value: "Отсутствует"},
    "GBP": {Value: "Отсутствует"},
    "AMD": {Value: "Отсутствует"},
    "BYN": {Value: "Отсутствует"},
    "BGN": {Value: "Отсутствует"},
    "BRL": {Value: "Отсутствует"},
    "HUF": {Value: "Отсутствует"},
    "HKD": {Value: "Отсутствует"},
    "DKK": {Value: "Отсутствует"},
    "USD": {Value: "Отсутствует"},
    "EUR": {Value: "Отсутствует"},
    "INR": {Value: "Отсутствует"},
    "KZT": {Value: "Отсутствует"},
    "CAD": {Value: "Отсутствует"},
    "KGS": {Value: "Отсутствует"},
    "CNY": {Value: "Отсутствует"},
    "MDL": {Value: "Отсутствует"},
    "NOK": {Value: "Отсутствует"},
    "PLN": {Value: "Отсутствует"},
    "RON": {Value: "Отсутствует"},
    "XDR": {Value: "Отсутствует"},
    "SGD": {Value: "Отсутствует"},
    "TJS": {Value: "Отсутствует"},
    "TRY": {Value: "Отсутствует"},
    "TMT": {Value: "Отсутствует"},
    "UZS": {Value: "Отсутствует"},
    "UAH": {Value: "Отсутствует"},
    "CZK": {Value: "Отсутствует"},
    "SEK": {Value: "Отсутствует"},
    "CHF": {Value: "Отсутствует"},
    "ZAR": {Value: "Отсутствует"},
    "KRW": {Value: "Отсутствует"},
    "JPY": {Value: "Отсутствует"}
}

export default errMsg;